services:
  traefik:
    container_name: born.traefik
    image: traefik:v3.6.1
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "5434:5432"
      - "8083:8083"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 10s

  whoami:
    container_name: born.whoami
    image: traefik/whoami
