version: '3.8'
services:
  hello-world:
    image: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_routing"
      - "traefik.http.routers.test.rule=Host(`hello-world.test`)"
      - "traefik.http.routers.test.entrypoints=web"
      - "traefik.http.services.test.loadbalancer.server.port=80"
      - "traefik.http.routers.test-https.rule=Host(`hello-world.test`)"
      - "traefik.http.routers.test-https.entrypoints=websecure"
      - "traefik.http.routers.test-https.tls=true"
    networks:
      - traefik
networks:
  traefik:
    name: traefik_routing
    external: true
